"""enough tables to login with about me and last seen in User table

Revision ID: 836d38d31ec5
Revises: 
Create Date: 2020-03-08 20:46:03.078366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836d38d31ec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('all_users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_users', 'last_seen')
    op.drop_column('all_users', 'about_me')
    # ### end Alembic commands ###
